service: atla-webscraper

frameworkVersion: '2'

package:
    individually: true

plugins:
    - serverless-offline

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: us-east-1

functions:
    character:
        handler: 'src/handlers/handler.getCharacterDetails'
        description: "Gets character's information"
        events:
            - http:
                  method: 'post'
                  path: 'character'
